backend:
    name: git-gateway
    branch: main # Branch to update (optional; defaults to master)
media_folder: "src/img" # Media files will be stored in the repo under images/uploads
public_folder: "assets/img"
collections:
    - label: "Pages"
      name: "pages"
      files:
          - label: "Home Page"
            name: "home"
            file: "src/_data/home.yaml"
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Intro, name: intro, widget: markdown }
                - label: Project
                  name: project
                  widget: list
                  fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Tags, name: tags, widget: string }
                      - {
                            label: Description,
                            name: description,
                            widget: markdown,
                        }
                      - { label: Photo, name: photo, widget: image }
          - label: "Test Page"
            name: "test"
            file: "src/_data/test.yaml"
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Intro, name: intro, widget: markdown }
                - { label: Cool Title, name: coolTitle, widget: string }
                - { label: Cool Content, name: cool, widget: markdown }
                - label: Projects
                  name: projects
                  widget: list
                  fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Tags, name: tags, widget: string }
                      - {
                            label: Description,
                            name: description,
                            widget: markdown,
                        }
                      - { label: Photo, name: photo, widget: image }
