backend:
    name: git-gateway
    branch: main # Branch to update (optional; defaults to master)
media_folder: "src/img" # Media files will be stored in the repo under images/uploads
public_folder: "assets/img"
# logo_url: https://your-site.com/images/logo.svg

 collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "site/content/home.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}