backend:
    name: git-gateway
    branch: main # Branch to update (optional; defaults to master)
media_folder: "src/img" # Media files will be stored in the repo under images/uploads
public_folder: "assets/img"
